kubeconfig_path: "/home/ec2-user/.kube/config"
helm_version: "3.14.4"
cert_manager_version: "v1.14.4"
rancher_version: "2.9.2"
rancher_hostname: "auto"  # set to "auto" to use this server's public IP with nip.io; override with your DNS name if desired
rancher_bootstrap_password: "Admin123!"
